apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prod-cert
  namespace: ambassador
spec:
  # Secret names are always required.
  secretName: prod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - AnalogSea
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
  - prod.analogsea.ca
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
