apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
  # BE CAREFUL WITH DEVICECLASS
  # deviceClass: hdd
