apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1

---

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: cephfs-pool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1
